-- MySQL Script generated by MySQL Workbench
-- Sat Apr  3 19:06:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Accounts` DEFAULT CHARACTER SET utf8 ;
USE `Accounts` ;

-- -----------------------------------------------------
-- Table `Accounts`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounts`.`Status` (
  `StatusID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounts`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounts`.`Account` (
  `AccountID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `IsUser` TINYINT NOT NULL,
  `StatusID` INT NOT NULL,
  PRIMARY KEY (`AccountID`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  INDEX `fk_Account_Status1_idx` (`StatusID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Status1`
    FOREIGN KEY (`StatusID`)
    REFERENCES `Accounts`.`Status` (`StatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounts`.`Password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounts`.`Password` (
  `PasswordID` INT NOT NULL AUTO_INCREMENT,
  `PasswordString` VARCHAR(60) NOT NULL,
  `OwnerID` INT NOT NULL,
  PRIMARY KEY (`PasswordID`),
  INDEX `fk_Password_Account_idx` (`OwnerID` ASC) VISIBLE,
  CONSTRAINT `fk_Password_Account`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `Accounts`.`Account` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'spotymeAdmin' IDENTIFIED BY 'proyectoredes';
GRANT ALL PRIVILEGES ON *.* TO 'spotymeAdmin'@'%' WITH GRANT OPTION;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

